--DROP DATABASE QuanLyThuVien
--DATABASE QuanLyThuVien
CREATE DATABASE QuanLyThuVien
GO
USE QuanLyThuVien

GO
SET DATEFORMAT DMY

--TABLE NHOMNGUOIDUNG
GO
CREATE TABLE NHOMNGUOIDUNG
(
	ID INT IDENTITY PRIMARY KEY,
	MANHOM AS CAST('NND' + RIGHT('000' + CAST(ID AS VARCHAR(3)), 3) AS CHAR(6)),
	TENNHOM NVARCHAR(100) NOT NULL
)

--TABLE CHUCNANG
GO
CREATE TABLE CHUCNANG
(
     ID INT PRIMARY KEY IDENTITY,
	 MACHUCNANG AS CAST('CN' + RIGHT('0000' + CAST(ID AS VARCHAR(4)), 4) AS CHAR(6)),
     TENCHUCNANG NVARCHAR(100) NOT NULL,
     TENMANHINHDUOCLOAD NVARCHAR(100) NOT NULL
)

--TABLE PHANQUYEN
GO
CREATE TABLE PHANQUYEN
(
    IDNHOMNGUOIDUNG INT NOT NULL,
	IDCHUCNANG INT NOT NULL,
    PRIMARY KEY (IDNHOMNGUOIDUNG, IDCHUCNANG),
	FOREIGN KEY (IDNHOMNGUOIDUNG) REFERENCES NHOMNGUOIDUNG(ID) ON DELETE CASCADE,
	FOREIGN KEY (IDCHUCNANG) REFERENCES CHUCNANG(ID) ON DELETE CASCADE

)

--TABLE NGUOIDUNG
GO
CREATE TABLE NGUOIDUNG
(
	ID INT IDENTITY PRIMARY KEY,
	MANGUOIDUNG AS CAST('ND'+ RIGHT('0000' + CAST(ID AS VARCHAR(4)), 4) AS CHAR(6)),
    TENNGUOIDUNG NVARCHAR(100) NOT NULL,
    TENDANGNHAP VARCHAR(100) UNIQUE NOT NULL,
    MATKHAU VARCHAR(100) NOT NULL,
    IDNHOMNGUOIDUNG INT NOT NULL,
	FOREIGN KEY (IDNHOMNGUOIDUNG) REFERENCES NHOMNGUOIDUNG(ID) ON DELETE CASCADE,
)

--TABLE THELOAI
GO
CREATE TABLE THELOAI
(
	ID INT IDENTITY PRIMARY KEY,
	MATHELOAI AS CAST('TL' + RIGHT('0000' + CAST(ID AS VARCHAR(4)), 4) AS CHAR(6)),  
	TENTHELOAI NVARCHAR(100) NOT NULL
)

--TABLE TACGIA
GO
CREATE TABLE TACGIA
(
	ID INT IDENTITY PRIMARY KEY,
	MATACGIA AS CAST('TG' + RIGHT('0000' + CAST(ID AS VARCHAR(4)), 4) AS CHAR(6)),
	TENTACGIA NVARCHAR(100) NOT NULL,
	NGAYSINH DATE NOT NULL
)

--TABLE SACH
GO
CREATE TABLE SACH
(
	ID INT IDENTITY PRIMARY KEY,
	MASACH AS CAST('SA' + RIGHT('0000' + CAST(ID AS VARCHAR(4)), 4) AS CHAR(6)),
	TENSACH NVARCHAR(100) NOT NULL,
	IDTHELOAI INT NOT NULL,
	NHAXUATBAN NVARCHAR(100) NOT NULL,
	NAMXUATBAN INT,
	SOLUONG INT NOT NULL, 
	GIATIEN INT NOT NULL, 
	FOREIGN KEY (IDTHELOAI) REFERENCES THELOAI(ID) ON DELETE CASCADE
)

--TABLE CT_TACGIA
GO
CREATE TABLE CT_TACGIA
(
	IDSACH INT,
	IDTACGIA INT,
	PRIMARY KEY (IDSACH, IDTACGIA),
	FOREIGN KEY (IDSACH)REFERENCES SACH(ID) ON DELETE CASCADE,
	FOREIGN KEY (IDTACGIA)REFERENCES TACGIA(ID) ON DELETE CASCADE,
)

--TABLE CUONSACH
GO
CREATE TABLE CUONSACH
(
	ID INT IDENTITY PRIMARY KEY,
	MACUONSACH AS CAST('CS'+ RIGHT('0000' + CAST(ID AS VARCHAR(4)), 4) AS CHAR(6)),
	IDSACH INT,
	TINHTRANG INT NOT NULL DEFAULT 1, --1 LA TRONG
	FOREIGN KEY (IDSACH) REFERENCES SACH(ID) ON DELETE CASCADE,
)

--TABLE PHIEUNHAPSACH
GO
CREATE TABLE PHIEUNHAPSACH
(
	ID INT IDENTITY PRIMARY KEY,
	SOPNS AS CAST('PNS' + RIGHT('0000' + CAST(ID AS VARCHAR(4)), 4) AS CHAR(7)),
	NGAYLAP DATE NOT NULL,
	TONGTIEN INT NOT NULL, 
)

--TABLE CT_PHIEUNHAP
GO
CREATE TABLE CT_PHIEUNHAPSACH
(
	IDPNS INT,
	IDSACH INT,
	SOLUONGNHAP INT NOT NULL, 
	DONGIA INT NOT NULL, 
	THANHTIEN INT NOT NULL, 
	PRIMARY KEY (IDPNS, IDSACH),
	FOREIGN KEY (IDPNS) REFERENCES PHIEUNHAPSACH(ID) ON DELETE CASCADE,
	FOREIGN KEY (IDSACH) REFERENCES SACH(ID) ON DELETE CASCADE,
)

--TABLE LOAIDOCGIA
GO
CREATE TABLE LOAIDOCGIA
(
	ID INT IDENTITY PRIMARY KEY,
	MALOAIDOCGIA  AS CAST('LDG'+ RIGHT('000' + CAST(ID AS VARCHAR(3)), 3) AS CHAR(6)),
	TENLOAIDOCGIA NVARCHAR(100) NOT NULL
)

--TABLE DOCGIA
GO
CREATE TABLE DOCGIA
(
	ID INT IDENTITY PRIMARY KEY,
	MADOCGIA AS CAST('DG' + RIGHT('0000' + CAST(ID AS VARCHAR(4)), 4) AS CHAR(6)),
	IDLOAIDOCGIA INT NOT NULL,
	TENDOCGIA NVARCHAR(100) NOT NULL,
	NGAYSINH DATE NOT NULL, 
	DIACHI NVARCHAR(100),
	EMAIL VARCHAR(100),
	NGAYLAPTHE DATE NOT NULL, 
	NGAYHETHAN DATE NOT NULL, 
	TONGNO INT NOT NULL DEFAULT 0,
	IDNGUOIDUNG INT NOT NULL,
	FOREIGN KEY (IDLOAIDOCGIA) REFERENCES LOAIDOCGIA(ID) ON DELETE CASCADE,
	FOREIGN KEY (IDNGUOIDUNG) REFERENCES NGUOIDUNG(ID) ON DELETE CASCADE,
)

--TABLE PHIEUMUONTRA
GO
CREATE TABLE PHIEUMUONTRA
(
	ID INT IDENTITY PRIMARY KEY,
	SOPMT AS CAST('PMT' + RIGHT('0000' + CAST(ID AS VARCHAR(4)), 4) AS CHAR(7)),
	IDDOCGIA INT NOT NULL,
	IDCUONSACH INT NOT NULL,
	NGAYMUON DATE NOT NULL, 
	NGAYPHAITRA DATE NOT NULL, 
	NGAYTRA DATE,
	TIENPHAT INT DEFAULT 0,
	FOREIGN KEY (IDDOCGIA) REFERENCES DOCGIA(ID) ON DELETE CASCADE,
	FOREIGN KEY (IDCUONSACH) REFERENCES CUONSACH(ID) ON DELETE CASCADE,
)

--TABLE PHIEUTHUTIENPHAT
GO
CREATE TABLE PHIEUTHUTIENPHAT
(
	ID INT IDENTITY PRIMARY KEY,
	SOPTTP AS CAST('PTT' + RIGHT('0000' + CAST(ID AS VARCHAR(4)), 4) AS CHAR(7)),
	IDDOCGIA INT NOT NULL,
	NGAYTHU DATE NOT NULL,
	TONGNO INT,
	SOTIENTHU INT NOT NULL DEFAULT 0,
	CONLAI INT NOT NULL
	FOREIGN KEY (IDDOCGIA) REFERENCES DOCGIA(ID) ON DELETE CASCADE,
)

--TABLE BC_TINHHINHMUONSACH
GO
CREATE TABLE BC_TINHHINHMUONSACH
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MABCTHMS AS CAST('BCMS' + RIGHT('0000' + CAST(ID AS VARCHAR(4)), 4) AS CHAR(8)),
	THANG INT NOT NULL, 
	NAM INT NOT NULL, 
	TONGSOLUOTMUON int NOT NULL DEFAULT 0
)

--TABLE CT_BC_TINHHINHMUONSACH
GO
CREATE TABLE CT_BC_TINHHINHMUONSACH
(
	IDBCTHMS INT NOT NULL,
	IDTHELOAI INT NOT NULL,
	SOLUOTMUON INT NOT NULL DEFAULT 0, 
	TILE NUMERIC(4,2) DEFAULT 0,
	PRIMARY KEY (IDBCTHMS, IDTHELOAI),
	FOREIGN KEY (IDBCTHMS) REFERENCES BC_TINHHINHMUONSACH(ID) ON DELETE CASCADE,
	FOREIGN KEY (IDTHELOAI) REFERENCES THELOAI(ID) ON DELETE CASCADE,
)

--TABLE BCSACHTRATRE
GO
CREATE TABLE BC_SACHTRATRE
(
	NGAY DATE NOT NULL,
	IDCUONSACH INT NOT NULL,
	NGAYMUON DATE NOT NULL,
	SONGAYTRATRE int NOT NULL DEFAULT 0,
	PRIMARY KEY(NGAY, IDCUONSACH),
	FOREIGN KEY (IDCUONSACH) REFERENCES CUONSACH(ID) ON DELETE CASCADE,
)

--TABLE THAMSO
GO
CREATE TABLE THAMSO
(
	ID INT IDENTITY PRIMARY KEY,
	TUOITOITHIEU INT DEFAULT 18, 
	TUOITOIDA INT DEFAULT 55, 
	THOIHANTHE INT DEFAULT 6, 
	KHOANGCACHNAMXB INT DEFAULT 8, 
	SONGAYMUONTOIDA INT DEFAULT 4, 
	SOSACHMUONTOIDA INT DEFAULT 5, 
	DONGIAPHAT INT DEFAULT 1000,
	APDUNGQDTIENTHU INT DEFAULT 1,
)

--INSERT NHOMNGUOIDUNG
GO
INSERT INTO NHOMNGUOIDUNG VALUES(N'Quản lý')
INSERT INTO NHOMNGUOIDUNG VALUES(N'Thủ thư')
INSERT INTO NHOMNGUOIDUNG VALUES(N'Độc giả')

--INSERT CHUCNANG
GO
INSERT INTO CHUCNANG VALUES(N'Quản Lý Độc Giả', N'Quản Lý Độc Giả')
INSERT INTO CHUCNANG VALUES(N'Quản Lý Sách', N'Quản Lý Sách')
INSERT INTO CHUCNANG VALUES(N'Quản Lý Phiếu Mượn Trả', N'Quản Lý Phiếu Mượn Trả')
INSERT INTO CHUCNANG VALUES(N'Quản Lý Phiếu Thu', N'Quản Lý Phiếu Thu')
INSERT INTO CHUCNANG VALUES(N'Báo Cáo Thống Kê', N'Báo Cáo Thống Kê')
INSERT INTO CHUCNANG VALUES(N'Quản Lý Người Dùng', N'Quản Lý Người Dùng')
INSERT INTO CHUCNANG VALUES(N'Thay Đổi Quy Định', N'Thay Đổi Quy Định')

INSERT INTO CHUCNANG VALUES(N'Tra Cứu Sách', N'Tra Cứu Sách')
INSERT INTO CHUCNANG VALUES(N'Thông Tin Sách Đã Mượn', N'Thông Tin Sách Đã Mượn')
INSERT INTO CHUCNANG VALUES(N'Thông Tin Phiếu Mượn Trả', N'Thông Tin Phiếu Mượn Trả')
INSERT INTO CHUCNANG VALUES(N'Thông Tin Phiếu Thu Tiền Phạt', N'Thông Tin Phiếu Thu Tiền Phạt')

--INSERT PHANQUYEN
GO
INSERT INTO PHANQUYEN VALUES(1, 1)
INSERT INTO PHANQUYEN VALUES(1, 2)
INSERT INTO PHANQUYEN VALUES(1, 3)
INSERT INTO PHANQUYEN VALUES(1, 4)
INSERT INTO PHANQUYEN VALUES(1, 5)
INSERT INTO PHANQUYEN VALUES(1, 6)
INSERT INTO PHANQUYEN VALUES(1, 7)

INSERT INTO PHANQUYEN VALUES(2, 1)
INSERT INTO PHANQUYEN VALUES(2, 2)
INSERT INTO PHANQUYEN VALUES(2, 3)
INSERT INTO PHANQUYEN VALUES(2, 4)
INSERT INTO PHANQUYEN VALUES(2, 5)

INSERT INTO PHANQUYEN VALUES(3, 8)
INSERT INTO PHANQUYEN VALUES(3, 9)
INSERT INTO PHANQUYEN VALUES(3, 10)
INSERT INTO PHANQUYEN VALUES(3, 11)

--INSERT NGUOIDUNG
GO
INSERT INTO NGUOIDUNG VALUES(N'Dương Gia Thiều', 'giathieu', 'admin', 1)
INSERT INTO NGUOIDUNG VALUES(N'Bùi Văn Thi', 'buithi', '123', 2)

INSERT INTO NGUOIDUNG VALUES(N'Nguyễn Đông Anh', 'donganh', '123', 3)
INSERT INTO NGUOIDUNG VALUES(N'Nguyễn Bá Kỳ Anh', 'kyanh', '123', 3)
INSERT INTO NGUOIDUNG VALUES(N'Đinh Vũ Minh Nhật', 'dinhnhat', '123', 3)

--INSERT LOAIDOCGIA
GO
INSERT INTO LOAIDOCGIA VALUES(N'Giảng viên')
INSERT INTO LOAIDOCGIA VALUES(N'Sinh viên')
INSERT INTO LOAIDOCGIA VALUES(N'Khác')

--INSERT DOCGIA
GO
INSERT INTO DOCGIA VALUES (1,N'Nguyễn Đông Anh','11/06/2003',N'Quận 1','dga@gmail.com','26/09/2022', '26/03/2023',11000,3)
INSERT INTO DOCGIA VALUES (2,N'Nguyễn Bá Kỳ Anh','26/09/2002',N'Thủ Đức','dgb@gmail.com','26/08/2022','26/03/2023',0,4)
INSERT INTO DOCGIA VALUES (3,N'Đinh Vũ Minh Nhật','24/02/2003',N'Quận 2','dgc@gmail.com','26/08/2022','26/02/2023',0,5)

--INSERT THAMSO
GO
INSERT INTO THAMSO VALUES (18, 55, 6, 8, 4, 5, 1000, 1)

--INSERT TACGIA
GO
INSERT INTO TACGIA VALUES (N'Lê Minh Quân','11/06/1993')
INSERT INTO TACGIA VALUES (N'Nguyễn Minh Đức','11/06/1981')
INSERT INTO TACGIA VALUES (N'Nguyễn Gia Tuấn Anh','11/06/1999')
INSERT INTO TACGIA VALUES (N'Phan Đình Duy','11/06/1987')

--INSERT THELOAI
GO
INSERT INTO THELOAI VALUES(N'Khoa Học')
INSERT INTO THELOAI VALUES(N'Bài Tập')
INSERT INTO THELOAI VALUES(N'Giáo trình')

--INSERT SACH
GO 
INSERT INTO SACH VALUES(N'Thiết Kế Hệ Thống Số HDL', 3, N'NXB', 2023, 100, 11000)
INSERT INTO SACH VALUES(N'Tư Tưởng Hồ Chí Minh', 3, N'NXB', 2023, 51, 12000)
INSERT INTO SACH VALUES(N'Thiết Kế Hệ Thống Nhúng', 1, N'NXB', 2023, 32, 13000)
INSERT INTO SACH VALUES(N'Nhập Môn Lập Trình', 2, N'NXB', 2023, 60, 14000)
INSERT INTO SACH VALUES(N'IOT và Ứng Dụng', 1, N'NXB', 2023, 45, 15000)

--INSERT CT_TACGIA
GO
INSERT INTO CT_TACGIA VALUES (1, 2)
INSERT INTO CT_TACGIA VALUES (1, 4)
INSERT INTO CT_TACGIA VALUES (2, 3)
INSERT INTO CT_TACGIA VALUES (3, 1)
INSERT INTO CT_TACGIA VALUES (3, 4)
INSERT INTO CT_TACGIA VALUES (3, 2)
INSERT INTO CT_TACGIA VALUES (4, 1)
INSERT INTO CT_TACGIA VALUES (5, 3)

--INSERT PHIEUNHAPSACH
GO 
INSERT INTO PHIEUNHAPSACH VALUES ('13/11/2023',287000)

INSERT INTO PHIEUNHAPSACH VALUES ('12/12/2023',121000)
INSERT INTO PHIEUNHAPSACH VALUES ('27/12/2023',48000)

--INSERT CT_PHIEUNHAPSACH
GO
INSERT INTO CT_PHIEUNHAPSACH VALUES (1, 2, 9, 12000, 108000) 
INSERT INTO CT_PHIEUNHAPSACH VALUES (1, 3, 8, 13000, 104000) 
INSERT INTO CT_PHIEUNHAPSACH VALUES (1, 5, 5, 15000, 75000) 

INSERT INTO CT_PHIEUNHAPSACH VALUES (2, 1, 10, 11000, 121000) 
INSERT INTO CT_PHIEUNHAPSACH VALUES (3, 2, 5, 12000, 48000) 

--INSERT CUONSACH
GO
INSERT INTO CUONSACH VALUES (1,0)
INSERT INTO CUONSACH VALUES (1,0)
INSERT INTO CUONSACH VALUES (1,0)
INSERT INTO CUONSACH VALUES (1,0)
INSERT INTO CUONSACH VALUES (1,0)
INSERT INTO CUONSACH VALUES (1,0)
INSERT INTO CUONSACH VALUES (1,1)
INSERT INTO CUONSACH VALUES (1,1)
INSERT INTO CUONSACH VALUES (1,1)
INSERT INTO CUONSACH VALUES (1,1)
INSERT INTO CUONSACH VALUES (1,1)
INSERT INTO CUONSACH VALUES (1,1)
INSERT INTO CUONSACH VALUES (1,1)
INSERT INTO CUONSACH VALUES (1,1)
INSERT INTO CUONSACH VALUES (1,1)
INSERT INTO CUONSACH VALUES (1,1)
INSERT INTO CUONSACH VALUES (1,1)
INSERT INTO CUONSACH VALUES (1,1)
INSERT INTO CUONSACH VALUES (1,1)
INSERT INTO CUONSACH VALUES (1,1)
INSERT INTO CUONSACH VALUES (1,1)
INSERT INTO CUONSACH VALUES (1,1)
INSERT INTO CUONSACH VALUES (1,1)
INSERT INTO CUONSACH VALUES (1,1)
INSERT INTO CUONSACH VALUES (1,1)
INSERT INTO CUONSACH VALUES (1,1)
INSERT INTO CUONSACH VALUES (1,1)
INSERT INTO CUONSACH VALUES (1,1)
INSERT INTO CUONSACH VALUES (1,1)
INSERT INTO CUONSACH VALUES (1,1)

INSERT INTO CUONSACH VALUES (2,1)
INSERT INTO CUONSACH VALUES (2,1)
INSERT INTO CUONSACH VALUES (2,1)
INSERT INTO CUONSACH VALUES (2,1)
INSERT INTO CUONSACH VALUES (2,1)
INSERT INTO CUONSACH VALUES (2,1)
INSERT INTO CUONSACH VALUES (2,1)
INSERT INTO CUONSACH VALUES (2,1)
INSERT INTO CUONSACH VALUES (2,1)
INSERT INTO CUONSACH VALUES (2,1)
INSERT INTO CUONSACH VALUES (2,1)
INSERT INTO CUONSACH VALUES (2,1)
INSERT INTO CUONSACH VALUES (2,1)
INSERT INTO CUONSACH VALUES (2,1)
INSERT INTO CUONSACH VALUES (2,1)
INSERT INTO CUONSACH VALUES (2,1)
INSERT INTO CUONSACH VALUES (2,1)
INSERT INTO CUONSACH VALUES (2,1)
INSERT INTO CUONSACH VALUES (2,1)
INSERT INTO CUONSACH VALUES (2,1)

INSERT INTO CUONSACH VALUES (3,1)
INSERT INTO CUONSACH VALUES (3,1)
INSERT INTO CUONSACH VALUES (3,1)
INSERT INTO CUONSACH VALUES (3,1)
INSERT INTO CUONSACH VALUES (3,1)
INSERT INTO CUONSACH VALUES (3,1)
INSERT INTO CUONSACH VALUES (3,1)
INSERT INTO CUONSACH VALUES (3,1)
INSERT INTO CUONSACH VALUES (3,1)
INSERT INTO CUONSACH VALUES (3,1)

INSERT INTO CUONSACH VALUES (4,1)
INSERT INTO CUONSACH VALUES (4,1)
INSERT INTO CUONSACH VALUES (4,1)
INSERT INTO CUONSACH VALUES (4,1)
INSERT INTO CUONSACH VALUES (4,1)
INSERT INTO CUONSACH VALUES (4,1)
INSERT INTO CUONSACH VALUES (4,1)
INSERT INTO CUONSACH VALUES (4,1)
INSERT INTO CUONSACH VALUES (4,1)
INSERT INTO CUONSACH VALUES (4,1)
INSERT INTO CUONSACH VALUES (4,1)
INSERT INTO CUONSACH VALUES (4,1)
INSERT INTO CUONSACH VALUES (4,1)
INSERT INTO CUONSACH VALUES (4,1)
INSERT INTO CUONSACH VALUES (4,1)

INSERT INTO CUONSACH VALUES (5,1)
INSERT INTO CUONSACH VALUES (5,1)
INSERT INTO CUONSACH VALUES (5,1)
INSERT INTO CUONSACH VALUES (5,1)
INSERT INTO CUONSACH VALUES (5,1)
INSERT INTO CUONSACH VALUES (5,1)
INSERT INTO CUONSACH VALUES (5,1)
INSERT INTO CUONSACH VALUES (5,1)
INSERT INTO CUONSACH VALUES (5,1)
INSERT INTO CUONSACH VALUES (5,1)
INSERT INTO CUONSACH VALUES (5,1)
INSERT INTO CUONSACH VALUES (5,1)
INSERT INTO CUONSACH VALUES (5,1)
INSERT INTO CUONSACH VALUES (5,1)
INSERT INTO CUONSACH VALUES (5,1)
INSERT INTO CUONSACH VALUES (5,1)
INSERT INTO CUONSACH VALUES (5,1)
INSERT INTO CUONSACH VALUES (5,1)
INSERT INTO CUONSACH VALUES (5,1)
INSERT INTO CUONSACH VALUES (5,1)
INSERT INTO CUONSACH VALUES (5,1)
INSERT INTO CUONSACH VALUES (5,1)
INSERT INTO CUONSACH VALUES (5,1)
INSERT INTO CUONSACH VALUES (5,1)
INSERT INTO CUONSACH VALUES (5,1)

--INSERT PHIEUMUONTRA
GO
INSERT INTO PHIEUMUONTRA VALUES(1,5,'08/11/2023', '12/11/2023', '15/11/2023', '3000')
INSERT INTO PHIEUMUONTRA VALUES(1,6,'08/11/2023', '12/11/2023', '16/11/2023', '4000')
INSERT INTO PHIEUMUONTRA VALUES(1,7,'08/11/2023', '12/11/2023', '17/11/2023', '5000')

INSERT INTO PHIEUMUONTRA VALUES(2,1,'08/11/2023', '12/11/2023', NULL, '0')
INSERT INTO PHIEUMUONTRA VALUES(2,2,'08/11/2023', '12/11/2023', NULL, '0')
INSERT INTO PHIEUMUONTRA VALUES(2,3,'08/11/2023', '12/11/2023', NULL, '0')

INSERT INTO PHIEUMUONTRA VALUES(3,5,'08/12/2023', '12/12/2023', NULL, '0')
INSERT INTO PHIEUMUONTRA VALUES(3,6,'08/12/2023', '12/12/2023', NULL, '0')
INSERT INTO PHIEUMUONTRA VALUES(3,7,'08/12/2023', '12/12/2023', NULL, '0')


